// Generated by CoffeeScript 1.9.1
exports.Perspective = (function() {
  var activated, allLayers, animationCurve, device, initialRotation, rotateObject, screen;

  function Perspective() {}

  animationCurve = "spring(120, 20, 0, 0.07)";

  activated = false;

  rotateObject = null;

  initialRotation = 0;

  screen = Framer.Device.screen;

  device = Framer.Device.phone;

  allLayers = null;

  Perspective.prototype.togglePerspective = function(verticalSeparation, temporalOpacity) {
    var i, j, layer, len, len1, ref, ref1, results, rotationNegative;
    if (verticalSeparation == null) {
      verticalSeparation = 40;
    }
    if (temporalOpacity == null) {
      temporalOpacity = 0.8;
    }
    allLayers = Framer.CurrentContext.getLayers();
    rotateObject = Framer.Device.deviceType !== "fullscreen" ? device : screen;
    this._eventsOn();
    if (!activated && !this._childrenAnimating(screen.children)) {
      activated = true;
      screen.clip = false;
      this._setAllLayersAsChildrenOf(screen);
      device.originalProps = device.props;
      device.animate({
        properties: {
          rotationZ: 45,
          rotationX: 45,
          scaleY: 0.86062,
          y: verticalSeparation * (allLayers.length / 3.4)
        },
        curve: animationCurve
      });
      ref = screen.children;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        layer = ref[i];
        layer.originalProps = layer.props;
        results.push(layer.animate({
          properties: {
            z: verticalSeparation * (layer.index - 1),
            opacity: temporalOpacity
          },
          delay: (allLayers.length - layer.index) / allLayers.length,
          curve: animationCurve
        }));
      }
      return results;
    } else if (activated && !this._childrenAnimating(screen.children)) {
      activated = false;
      this._eventsOff();
      rotationNegative = device.rotationZ < 0;
      if (Math.abs(device.rotationZ) > 180) {
        device.originalProps.rotationZ = rotationNegative ? -360 : 360;
      } else {
        device.originalProps.rotationZ = rotationNegative ? -0 : 0;
      }
      device.animate({
        properties: {
          rotationZ: device.originalProps.rotationZ,
          rotationX: device.originalProps.rotationX,
          scaleY: device.originalProps.scaleY,
          y: device.originalProps.y
        },
        curve: animationCurve
      });
      ref1 = screen.children;
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        layer = ref1[j];
        if (screen.children.indexOf(layer) !== 0) {
          layer.animate({
            properties: layer.originalProps,
            curve: animationCurve
          });
        }
      }
      return device.once(Events.AnimationEnd, function() {
        var k, len2, ref2, results1;
        screen.clip = true;
        ref2 = screen.children;
        results1 = [];
        for (k = 0, len2 = ref2.length; k < len2; k++) {
          layer = ref2[k];
          if (screen.children.indexOf(layer) !== 0) {
            results1.push(layer.parent = null);
          }
        }
        return results1;
      });
    }
  };

  Perspective.prototype._setAllLayersAsChildrenOf = function(parent) {
    var i, layer, len, results;
    results = [];
    for (i = 0, len = allLayers.length; i < len; i++) {
      layer = allLayers[i];
      if (layer.parent === null) {
        results.push(parent.addSubLayer(layer));
      }
    }
    return results;
  };

  Perspective.prototype._childrenAnimating = function(layersArray) {
    return _.some(layersArray, function(layer) {
      return layer.isAnimating;
    });
  };

  Perspective.prototype._panStart = function() {
    return initialRotation = rotateObject.rotationZ;
  };

  Perspective.prototype._pan = function(e) {
    return rotateObject.rotationZ = initialRotation - ((event.touchCenterX - event.startX) / 4);
  };

  Perspective.prototype._panEnd = function() {
    return rotateObject.rotationZ = rotateObject.rotationZ % 360;
  };

  Perspective.prototype._eventsOn = function() {
    if (rotateObject === screen) {
      rotateObject.animate({
        properties: {
          backgroundColor: "rgba(128, 128, 128, 0.2)"
        }
      });
    }
    rotateObject.on(Events.PanStart, this._panStart);
    rotateObject.on(Events.Pan, this._pan);
    return rotateObject.on(Events.PanEnd, this._panEnd);
  };

  Perspective.prototype._eventsOff = function() {
    if (rotateObject === screen) {
      rotateObject.animate({
        properties: {
          backgroundColor: "transparent"
        }
      });
    }
    rotateObject.off(Events.PanStart, this._panStart);
    rotateObject.off(Events.Pan, this._pan);
    return rotateObject.off(Events.PanEnd, this._panEnd);
  };

  return Perspective;

})();
